import type { DraftOrder, DraftPick, NormalizedDashboardInput, Player } from "@/lib/domain";

export const myTeamName = "Quebec Voyageurs";

export const myRoster: Player[] = [
  {
    id: "voy-01",
    name: "Alexei Volkov",
    team: myTeamName,
    position: "C",
    role: "First-line play driver",
    age: 27,
    capHit: 8.4,
    yearsRemaining: 1,
    contractStatus: "ufa",
    performance: 91,
    playDriving: 88,
    defense: 71,
    specialTeams: 86,
    chemistryFit: 84,
    upside: 74,
  },
  {
    id: "voy-02",
    name: "Matias Belliveau",
    team: myTeamName,
    position: "LW",
    role: "Middle-six finisher",
    age: 24,
    capHit: 4.1,
    yearsRemaining: 2,
    contractStatus: "signed",
    performance: 76,
    playDriving: 72,
    defense: 56,
    specialTeams: 68,
    chemistryFit: 79,
    upside: 81,
  },
  {
    id: "voy-03",
    name: "Noah Mercer",
    team: myTeamName,
    position: "RW",
    role: "Top-six transition winger",
    age: 22,
    capHit: 1.3,
    yearsRemaining: 1,
    contractStatus: "rfa",
    performance: 71,
    playDriving: 74,
    defense: 58,
    specialTeams: 59,
    chemistryFit: 76,
    upside: 89,
  },
  {
    id: "voy-04",
    name: "Evan Salo",
    team: myTeamName,
    position: "LD",
    role: "Matchup defenseman",
    age: 29,
    capHit: 5.2,
    yearsRemaining: 3,
    contractStatus: "signed",
    performance: 78,
    playDriving: 69,
    defense: 86,
    specialTeams: 65,
    chemistryFit: 73,
    upside: 61,
  },
  {
    id: "voy-05",
    name: "Luca Strand",
    team: myTeamName,
    position: "RD",
    role: "Second-pair puck mover",
    age: 25,
    capHit: 3.7,
    yearsRemaining: 2,
    contractStatus: "signed",
    performance: 73,
    playDriving: 78,
    defense: 67,
    specialTeams: 63,
    chemistryFit: 82,
    upside: 77,
  },
  {
    id: "voy-06",
    name: "Tomas Hruby",
    team: myTeamName,
    position: "G",
    role: "Starter",
    age: 30,
    capHit: 6.6,
    yearsRemaining: 4,
    contractStatus: "signed",
    performance: 80,
    playDriving: 52,
    defense: 84,
    specialTeams: 78,
    chemistryFit: 68,
    upside: 55,
  },
  {
    id: "voy-07",
    name: "Julien Cormier",
    team: myTeamName,
    position: "C",
    role: "Two-way prospect",
    age: 20,
    capHit: 0.95,
    yearsRemaining: 3,
    contractStatus: "prospect",
    inMinors: true,
    performance: 54,
    playDriving: 63,
    defense: 61,
    specialTeams: 49,
    chemistryFit: 70,
    upside: 87,
  },
  {
    id: "voy-08",
    name: "Mikko Vesa",
    team: myTeamName,
    position: "RW",
    role: "Boom-bust wing prospect",
    age: 19,
    capHit: 0.9,
    yearsRemaining: 3,
    contractStatus: "prospect",
    inMinors: true,
    performance: 48,
    playDriving: 59,
    defense: 44,
    specialTeams: 58,
    chemistryFit: 65,
    upside: 91,
  },
];

export const leagueTargets: Player[] = [
  {
    id: "oth-01",
    name: "Dylan Ritchie",
    team: "Halifax Admirals",
    position: "LD",
    role: "Top-four transition defender",
    age: 26,
    capHit: 4.4,
    yearsRemaining: 2,
    contractStatus: "signed",
    performance: 77,
    playDriving: 82,
    defense: 74,
    specialTeams: 68,
    chemistryFit: 79,
    upside: 72,
  },
  {
    id: "oth-02",
    name: "Carter Lindholm",
    team: "Red Deer Kings",
    position: "RW",
    role: "Net-front scorer",
    age: 28,
    capHit: 6.2,
    yearsRemaining: 1,
    contractStatus: "ufa",
    performance: 83,
    playDriving: 71,
    defense: 53,
    specialTeams: 79,
    chemistryFit: 74,
    upside: 62,
  },
  {
    id: "oth-03",
    name: "Anton Hasek",
    team: "Seattle Orcas",
    position: "C",
    role: "Middle-six matchup center",
    age: 23,
    capHit: 2.2,
    yearsRemaining: 2,
    contractStatus: "signed",
    performance: 69,
    playDriving: 73,
    defense: 78,
    specialTeams: 61,
    chemistryFit: 81,
    upside: 84,
  },
  {
    id: "oth-04",
    name: "Mason Gauthier",
    team: "Moncton Mariners",
    position: "G",
    role: "High-variance tandem goalie",
    age: 24,
    capHit: 2.9,
    yearsRemaining: 1,
    contractStatus: "rfa",
    performance: 74,
    playDriving: 45,
    defense: 79,
    specialTeams: 67,
    chemistryFit: 66,
    upside: 83,
  },
];

export const draftPicks: DraftPick[] = [
  {
    id: "pick-2027-1",
    team: myTeamName,
    season: 2027,
    round: 1,
    projectedSlot: 9,
  },
  {
    id: "pick-2027-2",
    team: myTeamName,
    season: 2027,
    round: 2,
    projectedSlot: 9,
  },
  {
    id: "pick-2028-1",
    team: myTeamName,
    season: 2028,
    round: 1,
    projectedSlot: 15,
  },
  {
    id: "pick-2027-sjs-2",
    team: myTeamName,
    issuerTeam: "San Jose Sharks",
    season: 2027,
    round: 2,
    projectedSlot: 5,
  },
];

export const draftOrders: DraftOrder[] = [
  {
    team: myTeamName,
    season: new Date().getFullYear(),
    projectedSlot: 9,
  },
  {
    team: "Halifax Admirals",
    season: new Date().getFullYear(),
    projectedSlot: 12,
  },
  {
    team: "Moncton Mariners",
    season: new Date().getFullYear(),
    projectedSlot: 18,
  },
  {
    team: "Red Deer Kings",
    season: new Date().getFullYear(),
    projectedSlot: 7,
  },
  {
    team: "San Jose Sharks",
    season: new Date().getFullYear(),
    projectedSlot: 5,
  },
  {
    team: "Seattle Orcas",
    season: new Date().getFullYear(),
    projectedSlot: 15,
  },
];

export const demoDashboardInput: NormalizedDashboardInput = {
  teamName: myTeamName,
  roster: myRoster,
  leagueTargets,
  draftPicks,
  draftOrders,
  finances: {
    contractPenalties: 1.2,
    injuredRelief: 0,
  },
};